#include <iostream>

#include "leetcode/2.h"
#include "leetcode/5.h"
#include "leetcode/14.h"
#include "leetcode/15.h"
#include "leetcode/19.h"
#include "leetcode/21.h"
#include "leetcode/23.h"
#include "leetcode/25.h"
#include "leetcode/26.h"
#include "leetcode/27.h"
#include "leetcode/48.h"
#include "leetcode/54.h"
#include "leetcode/59.h"
#include "leetcode/61.h"
#include "leetcode/80.h"
#include "leetcode/82.h"
#include "leetcode/83.h"
#include "leetcode/86.h"
#include "leetcode/88.h"
#include "leetcode/92.h"
#include "leetcode/125.h"
#include "leetcode/151.h"
#include "leetcode/167.h"
#include "leetcode/206.h"
#include "leetcode/234.h"
#include "leetcode/283.h"
#include "leetcode/287.h"
#include "leetcode/303.h"
#include "leetcode/304.h"
#include "leetcode/373.h"
#include "leetcode/378.h"
#include "leetcode/445.h"
#include "leetcode/876.h"

int main() {
    leetcode304::test();
    return 0;
}